os: linux
dist: bionic
services:
  - xvfb
language: cpp
compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsfml-dev
script:
  - echo ${DISPLAY}
  - make debug
  - make clean
  - make release
  - make clean
  - export BUILD_TEST=true
  - make
  - ./littleworld